
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://yamabiko.proxy.rlwy.net:24607/railway?useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true
    username: root
    password: jvoGWIXVeNkXmUMLNbBnFyxhVErqZjaW
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
